apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-app
spec:
  containers:
  - name: nextjs-app
    image: gcr.io/gcp-kubernetes-cluster-415821/nextjs-app:v1
    ports:
    - containerPort: 3000
    env:
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: url
    - name: DATABASE_USER
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: user
    - name: DATABASE_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-credentials
          key: password
