apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # The values must be base64 encoded
  database-url: <base64-encoded-database-url>
  database-user: <base64-encoded-database-username>
  database-password: <base64-encoded-database-password>
